---
- hosts: all
  become: true
  vars:
    jenkins_hostname: localhost
    jenkins_plugins:
      - blueocean
      - greenballs
    jenkins_plugin_timeout: 120
  roles:
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"
    java_packages:
      - java-1.8.0-openjdk
  - role: geerlingguy.jenkins
